import MainLayout from "@/components/layout";
import { Layout } from "antd";
import Head from "next/head";

const UserProfile = () => {
  return <div>this is protected user profile</div>;
};

export default UserProfile;


UserProfile.getLayout = function getLayout(page) {
  return (
    <Layout>
      <Head>
        <title>User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{page}</MainLayout>
    </Layout>
  );
};