import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import MainLayout from "@/components/layout";
import { Layout } from "antd";
const inter = Inter({ subsets: ["latin"] });

export default function Page() {
  return (
    <>
      <div>this is home</div>
    </>
  );
}

Page.getLayout = function getLayout(page) {
  return (
    <Layout>
      <Head>
        <title>PC Builder Paradox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{page}</MainLayout>
    </Layout>
  );
};
